version: '3'

volumes:
  pg_data:
  static_volume:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: atedzi/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/media

  frontend:
    image: atedzi/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: atedzi/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/media
    ports:
      - 9000:80