version: '3'

volumes:
  # pg_data_production:
  # static_production:
  # media_production:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      # - pg_data_production:/var/lib/postgresql/data
      - pg_data:/var/lib/postgres/data

  backend:
    image: atedzi/kittygram_backend
    env_file: .env
    volumes:
      # - static_production:/backend_static/
      # - media_production:/app/media/
      - static:/static/
      - media:/app/media/
    # depends_on:
    #   - db

  frontend:
    image: atedzi/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      # - static_production:/frontend_static
      - static:/static

  gateway:
    image: atedzi/kittygram_gateway
    env_file: .env
    volumes:
      # - static_production:/staticfiles/
      - static:/static
      - production:/app/media/
    ports:
      - 9000:80
    # depends_on:
    #   - backend